name: Secrets Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Expect, jq and Python
        run: sudo apt-get install -y expect jq python3 python3-pip  wkhtmltopdf

      - name: Install Python packages
        run: pip install pandas json2html tabulate

      - name: Install Talisman
        run: |
          curl --silent https://thoughtworks.github.io/talisman/scripts/install.bash > install.bash
          chmod +x install.bash
          expect -c '
          set timeout -1
          spawn ./install.bash --pre-push
          expect "PLEASE CHOOSE WHERE YOU WISH TO SET TALISMAN_HOME VARIABLE AND talisman binary PATH (Enter option number): "
          send "4\r"
          expect "No git template directory is configured. Let'\''s add one."
          send "1\r"
          interact
          '

      - name: Run Talisman
        id: run_talisman
        run: ~/.talisman/bin/talisman_linux_amd64 --scan
        continue-on-error: true
      
      - name: Convert JSON to HTML
        run: |
          python3 -c "
          import json
          import os
          from json2html import *
          with open('talisman_report/talisman_reports/data/report.json') as f:
              data = json.load(f)
          html = json2html.convert(json = data)
          os.makedirs('talisman_html_report', exist_ok=True)
          with open('talisman_html_report/report.html', 'w') as f:
              f.write(html)
          " && wkhtmltopdf talisman_html_report/report.html talisman_report.pdf
      
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: talisman-report-pdf
          path: talisman_report.pdf

      - name: Check the status of talisman scan
        run: |
          if [[ ${{ steps.run_talisman.outcome }} == "success" ]]; then exit 0; else echo "Download the Talisman scan report from Artifact" && exit 1; fi
